import { useState, useEffect } from "react";
import {
  Compass,
  Calendar,
  Users,
  DollarSign,
  MapPin,
  Star,
  Coffee,
  Cloud,
  Shield,
  CheckSquare,
  Download,
  Share2,
  RotateCcw,
  Hotel,
  Utensils,
  ChevronDown,
  ChevronUp,
  Bus,
  Map,
  ArrowRight,
  Sparkles,
  Info
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { TripPlan, TripSearchParams } from "../types";

interface TripResultsProps {
  plan: TripPlan;
  searchParams: TripSearchParams;
  onReset: () => void;
}

export default function TripResults({ plan, searchParams, onReset }: TripResultsProps) {
  const [posterUrl, setPosterUrl] = useState<string>("");
  const [loadingPoster, setLoadingPoster] = useState<boolean>(true);
  const [posterMessage, setPosterMessage] = useState<string>("");
  const [activeDay, setActiveDay] = useState<number>(1);
  const [shareToast, setShareToast] = useState<boolean>(false);

  // Trigger travel poster generation on load
  useEffect(() => {
    let active = true;
    const fetchPoster = async () => {
      try {
        setLoadingPoster(true);
        const res = await fetch("/api/generate-poster", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            destination: plan.destinationName,
            prompt: plan.posterConceptPrompt,
          }),
        });
        const data = await res.json();
        if (active) {
          if (data.imageUrl) {
            setPosterUrl(data.imageUrl);
          }
          if (data.message) {
            setPosterMessage(data.message);
          }
          setLoadingPoster(false);
        }
      } catch (err) {
        console.error("Error loading poster:", err);
        if (active) {
          setPosterUrl("https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1200&q=80");
          setLoadingPoster(false);
        }
      }
    };

    fetchPoster();
    return () => {
      active = false;
    };
  }, [plan]);

  // Download trip plan as a formatted Markdown document
  const handleDownload = () => {
    let md = `# Travel Plan for ${plan.destinationName} (${searchParams.days} Days)\n`;
    md += `*Generated by VoyageAI - Plan. Visualize. Travel.*\n\n`;
    md += `## Trip Overview\n${plan.overview}\n\n`;
    md += `### Highlights\n` + plan.highlights.map((h) => `- ${h}`).join("\n") + "\n\n";

    md += `## Budget Breakdown\n`;
    md += `**Total Estimated Cost:** ${plan.budget.totalEstimatedCost} ${plan.budget.currency}\n\n`;
    plan.budget.categories.forEach((cat) => {
      md += `- **${cat.category}:** ${cat.amount} (${cat.percentage}%)\n  *${cat.description || ""}*\n`;
    });
    md += "\n";

    md += `## Day-by-Day Itinerary\n`;
    plan.itinerary.forEach((dayPlan) => {
      md += `### Day ${dayPlan.day}: ${dayPlan.title}\n`;
      dayPlan.activities.forEach((act) => {
        md += `- **${act.time}:** ${act.title}\n  ${act.description}\n`;
        if (act.costEstimate) md += `  *Estimated cost:* ${act.costEstimate}\n`;
      });
      md += "\n";
    });

    md += `## Hotel Recommendations\n`;
    plan.hotels.forEach((hotel) => {
      md += `### ${hotel.name}\n- **Price Range:** ${hotel.priceRange}\n- **Rating:** ${hotel.rating}\n- ${hotel.description}\n`;
      if (hotel.location) md += `- **Location:** ${hotel.location}\n`;
      md += "\n";
    });

    md += `## Restaurant Recommendations\n`;
    plan.restaurants.forEach((rest) => {
      md += `### ${rest.name}\n- **Cuisine:** ${rest.cuisine}\n- **Price Range:** ${rest.priceRange}\n- **Rating:** ${rest.rating}\n- **Recommended Dish:** ${rest.recommendedDish}\n- ${rest.description}\n\n`;
    });

    md += `## Tourist Attractions\n`;
    plan.attractions.forEach((attr) => {
      md += `### ${attr.name}\n- ${attr.description}\n`;
      if (attr.duration) md += `- **Suggested Duration:** ${attr.duration}\n`;
      if (attr.cost) md += `- **Entrance Cost:** ${attr.cost}\n`;
      if (attr.highlights) md += `- **Highlights:** ${attr.highlights}\n`;
      md += "\n";
    });

    md += `## Travel Tips & Logistics\n`;
    md += `### Transportation\n${plan.transportation}\n\n`;
    md += `### Weather Tips\n${plan.weatherTips}\n\n`;

    md += `### Packing Checklist\n` + plan.packingChecklist.map((i) => `- [ ] ${i}`).join("\n") + "\n\n";
    md += `### Safety Guidelines\n` + plan.safetyTips.map((s) => `- ${s}`).join("\n") + "\n";

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `VoyageAI_Plan_${plan.destinationName.replace(/[^a-zA-Z0-9]/g, "_")}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    const text = `Check out my customized ${searchParams.days}-day trip to ${plan.destinationName} planned with VoyageAI!`;
    navigator.clipboard.writeText(`${text} Explore here: ${window.location.href}`);
    setShareToast(true);
    setTimeout(() => setShareToast(false), 3000);
  };

  return (
    <div className="space-y-12">
      {/* 1. Header Banner & Poster Section */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
        {/* Left Side: Destination Overview */}
        <div className="lg:col-span-7 flex flex-col justify-center space-y-6">
          <div className="space-y-3">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 bg-blue-50 dark:bg-blue-950/40 text-blue-900 dark:text-blue-300 text-xs font-bold uppercase tracking-widest rounded-full border border-blue-200/40">
              <Sparkles className="h-3.5 w-3.5 text-blue-600 dark:text-blue-400" />
              <span>AI Custom Guidebook</span>
            </span>
            <h1 className="text-4xl md:text-6xl font-light text-slate-900 dark:text-white tracking-tight serif italic">
              {plan.destinationName}
            </h1>
          </div>

          <div className="flex flex-wrap gap-4 text-sm text-slate-500 dark:text-slate-400 font-medium">
            <span className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 px-3.5 py-2 rounded-xl border border-slate-200/50 dark:border-slate-700/50">
              <Calendar className="h-4.5 w-4.5 text-blue-500" />
              {searchParams.days} Days
            </span>
            <span className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 px-3.5 py-2 rounded-xl border border-slate-200/50 dark:border-slate-700/50">
              <Users className="h-4.5 w-4.5 text-blue-500" />
              {searchParams.travelers} {searchParams.travelers === 1 ? "Traveler" : "Travelers"}
            </span>
            <span className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 px-3.5 py-2 rounded-xl border border-slate-200/50 dark:border-slate-700/50">
              <DollarSign className="h-4.5 w-4.5 text-blue-500" />
              {searchParams.budget} Budget
            </span>
            <span className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 px-3.5 py-2 rounded-xl border border-slate-200/50 dark:border-slate-700/50">
              <Compass className="h-4.5 w-4.5 text-blue-500" />
              {searchParams.travelStyle} Style
            </span>
          </div>

          <div className="space-y-3">
            <h2 className="text-2xl serif font-semibold text-blue-900 dark:text-blue-300 pb-2 border-b border-slate-100 dark:border-slate-800/80">Destination Overview</h2>
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed text-base">
              {plan.overview}
            </p>
          </div>

          <div className="space-y-3">
            <h3 className="text-sm uppercase font-semibold tracking-wider text-slate-400">Trip Highlights</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
              {plan.highlights.map((hl, index) => (
                <div key={index} className="flex items-start gap-2 text-sm text-slate-700 dark:text-slate-300 bg-slate-50 dark:bg-slate-800/50 p-2.5 rounded-xl border border-slate-100 dark:border-slate-800/80">
                  <ArrowRight className="h-4 w-4 text-blue-500 shrink-0 mt-0.5" />
                  <span>{hl}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Side: Travel Poster Display */}
        <div className="lg:col-span-5 flex flex-col items-center">
          <div className="relative w-full max-w-xs aspect-3/4 rounded-3xl overflow-hidden bg-slate-100 dark:bg-slate-800 border-4 border-white dark:border-slate-900 shadow-2xl flex flex-col justify-center items-center">
            {loadingPoster ? (
              <div className="p-8 text-center space-y-4">
                <div className="relative flex justify-center">
                  <Compass className="h-12 w-12 text-blue-500 animate-spin" />
                  <Sparkles className="absolute -top-1 -right-1 h-5 w-5 text-amber-500 animate-pulse" />
                </div>
                <div className="space-y-1">
                  <p className="font-semibold text-slate-800 dark:text-white">Generating Travel Poster...</p>
                  <p className="text-xs text-slate-400">Designing modern vector art for {plan.destinationName}</p>
                </div>
              </div>
            ) : (
              <>
                <div className="absolute top-4 left-4 px-3 py-1 glass rounded-full text-[9px] uppercase font-bold tracking-widest text-blue-900 shadow-xs z-10">
                  AI Travel Poster No. {Math.floor(Math.random() * 80 + 10)}
                </div>
                <img
                  src={posterUrl}
                  alt={`AI generated travel poster for ${plan.destinationName}`}
                  referrerPolicy="no-referrer"
                  className="w-full h-full object-cover select-none transition-transform duration-500 hover:scale-105"
                />
                {/* Decorative retro banner overlay */}
                <div className="absolute bottom-0 inset-x-0 bg-linear-to-t from-black/85 via-black/50 to-transparent p-5 text-center text-white">
                  <p className="text-2xs uppercase tracking-widest text-slate-300 font-medium">VoyageAI Poster Series</p>
                  <p className="text-2xl font-light tracking-tight serif italic mt-1">{plan.destinationName}</p>
                </div>
              </>
            )}
          </div>
          {posterMessage && (
            <div className="mt-3 flex items-start gap-2 max-w-xs bg-slate-50 dark:bg-slate-800/50 p-2.5 rounded-xl border border-slate-100 dark:border-slate-800/60">
              <Info className="h-4 w-4 text-slate-400 shrink-0 mt-0.5" />
              <p className="text-[11px] text-slate-500 dark:text-slate-400 leading-tight">{posterMessage}</p>
            </div>
          )}
        </div>
      </div>

      {/* 2. Timeline Itinerary */}
      <div className="space-y-6">
        <div className="flex items-center gap-3 border-b border-slate-200 dark:border-slate-800 pb-4">
          <div className="p-2.5 bg-blue-50 dark:bg-blue-950/30 text-blue-900 dark:text-blue-400 rounded-lg">
            <Map className="h-5 w-5" />
          </div>
          <div>
            <h2 className="text-2xl md:text-3xl font-light text-blue-900 dark:text-blue-300 serif">Curated <span className="italic">Itinerary</span></h2>
            <p className="text-xs uppercase tracking-wider text-slate-400 dark:text-slate-500 font-medium">Perfect travel schedule engineered for your travel style.</p>
          </div>
        </div>

        {/* Days Selector tabs */}
        <div className="flex gap-2 overflow-x-auto pb-2 scrollbar-none">
          {plan.itinerary.map((dayPlan) => (
            <button
              key={dayPlan.day}
              onClick={() => setActiveDay(dayPlan.day)}
              className={`px-5 py-2 rounded-full font-semibold transition-all shrink-0 text-sm focus:outline-hidden ${
                activeDay === dayPlan.day
                  ? "bg-blue-900 dark:bg-blue-800 text-white shadow-md"
                  : "bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 border border-slate-200/40 dark:border-slate-700"
              }`}
            >
              Day 0{dayPlan.day}
            </button>
          ))}
        </div>

        {/* Active day detail content */}
        <AnimatePresence mode="wait">
          {plan.itinerary.map((dayPlan) => {
            if (dayPlan.day !== activeDay) return null;
            return (
              <motion.div
                key={dayPlan.day}
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -15 }}
                transition={{ duration: 0.3 }}
                className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-sm space-y-6"
              >
                <div className="border-b border-slate-150 dark:border-slate-800 pb-3">
                  <h3 className="text-xl md:text-2xl font-light text-blue-950 dark:text-blue-200 serif">
                    Day 0{dayPlan.day} — <span className="italic font-normal text-blue-900 dark:text-blue-300">{dayPlan.title}</span>
                  </h3>
                </div>

                <div className="relative border-l-2 border-blue-500/30 pl-6 ml-3 space-y-8 py-2">
                  {dayPlan.activities.map((act, index) => (
                    <div key={index} className="relative">
                      {/* Timeline Dot */}
                      <span className="absolute -left-[31px] top-1.5 flex h-3.5 w-3.5 items-center justify-center rounded-full bg-blue-900 dark:bg-blue-400 border-2 border-blue-100 dark:border-blue-950 ring-4 ring-white dark:ring-slate-900" />

                      <div className="space-y-1.5">
                        <div className="flex flex-wrap items-center gap-2.5">
                          <span className="text-[10px] font-bold text-blue-900 dark:text-blue-400 uppercase tracking-widest bg-blue-50 dark:bg-blue-950/40 px-2 py-0.5 rounded border border-blue-100/30">
                            {act.time}
                          </span>
                          <h4 className="font-semibold text-slate-950 dark:text-white text-base serif italic">
                            {act.title}
                          </h4>
                          {act.costEstimate && (
                            <span className="text-[10px] bg-slate-50 dark:bg-slate-800 text-slate-500 dark:text-slate-400 px-2 py-0.5 rounded-md font-bold uppercase tracking-wider border border-slate-200/40">
                              {act.costEstimate}
                            </span>
                          )}
                        </div>
                        <p className="text-slate-600 dark:text-slate-300 text-sm leading-relaxed">
                          {act.description}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </div>

      {/* 3. Budget Cards */}
      <div className="space-y-6">
        <div className="flex items-center gap-3 border-b border-slate-200 dark:border-slate-800 pb-4">
          <div className="p-2.5 bg-blue-50 dark:bg-blue-950/30 text-blue-900 dark:text-blue-400 rounded-lg">
            <DollarSign className="h-5 w-5" />
          </div>
          <div>
            <h2 className="text-2xl md:text-3xl font-light text-blue-900 dark:text-blue-300 serif">Budget <span className="italic">Allocation</span></h2>
            <p className="text-xs uppercase tracking-wider text-slate-400 dark:text-slate-500 font-medium">Intelligent cost projection and spending advice.</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Total Cost Display card */}
          <div className="bg-linear-to-br from-blue-900 to-indigo-950 text-white rounded-3xl p-6 shadow-md flex flex-col justify-between border border-blue-900">
            <div className="space-y-2">
              <p className="text-xs uppercase tracking-wider text-blue-100 font-semibold">Total Cost Projection</p>
              <h3 className="text-4xl font-light tracking-tight serif italic text-white">
                {plan.budget.totalEstimatedCost} <span className="text-xs uppercase tracking-wider font-sans font-medium text-blue-200">{plan.budget.currency}</span>
              </h3>
            </div>
            <div className="pt-8 border-t border-white/10 text-xs text-blue-100">
              *Estimates are calculated based on a {searchParams.travelStyle} stay for {searchParams.travelers} {searchParams.travelers === 1 ? "person" : "people"}.
            </div>
          </div>

          {/* Individual Category Cards */}
          <div className="md:col-span-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-sm space-y-4">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">Expense Breakdown</h4>
            <div className="space-y-4.5">
              {plan.budget.categories.map((cat, idx) => (
                <div key={idx} className="space-y-1.5">
                  <div className="flex justify-between items-center text-sm font-semibold">
                    <span className="text-slate-700 dark:text-slate-300">{cat.category}</span>
                    <span className="text-slate-900 dark:text-white font-bold">{cat.amount} ({cat.percentage}%)</span>
                  </div>
                  {/* Visual percentage bar */}
                  <div className="w-full h-2 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-blue-500 rounded-full transition-all duration-500"
                      style={{ width: `${cat.percentage}%` }}
                    />
                  </div>
                  {cat.description && (
                    <p className="text-xs text-slate-400 dark:text-slate-500 italic leading-snug">{cat.description}</p>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* 4. Hotels & Restaurants Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Curated Stays */}
        <div className="space-y-6">
          <div className="flex items-center gap-3 border-b border-slate-200 dark:border-slate-800 pb-4">
            <div className="p-2.5 bg-blue-50 dark:bg-blue-950/30 text-blue-900 dark:text-blue-400 rounded-lg">
              <Hotel className="h-5 w-5" />
            </div>
            <div>
              <h2 className="text-xl md:text-2xl font-light text-blue-900 dark:text-blue-300 serif">Bespoke <span className="italic">Accommodations</span></h2>
              <p className="text-xs uppercase tracking-wider text-slate-400 dark:text-slate-500 font-medium">Top-rated hotels aligned with your parameters.</p>
            </div>
          </div>

          <div className="space-y-4">
            {plan.hotels.map((hotel, index) => (
              <div key={index} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 shadow-sm space-y-3 hover:border-blue-400/50 dark:hover:border-blue-800/50 transition-colors">
                <div className="flex justify-between items-start gap-2">
                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white text-base serif italic">{hotel.name}</h3>
                    {hotel.location && (
                      <p className="text-xs text-slate-400 flex items-center gap-1 mt-0.5">
                        <MapPin className="h-3 w-3 shrink-0" /> {hotel.location}
                      </p>
                    )}
                  </div>
                  <div className="flex flex-col items-end shrink-0">
                    <span className="inline-flex items-center gap-1 bg-amber-50 dark:bg-amber-950/20 text-amber-600 dark:text-amber-400 text-xs px-2 py-0.5 rounded-sm font-semibold">
                      <Star className="h-3 w-3 fill-amber-500 text-amber-500" /> {hotel.rating}
                    </span>
                    <span className="text-xs font-bold text-blue-600 dark:text-blue-400 mt-1">{hotel.priceRange}</span>
                  </div>
                </div>
                <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                  {hotel.description}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* Restaurants Recommendations */}
        <div className="space-y-6">
          <div className="flex items-center gap-3 border-b border-slate-200 dark:border-slate-800 pb-4">
            <div className="p-2.5 bg-blue-50 dark:bg-blue-950/30 text-blue-900 dark:text-blue-400 rounded-lg">
              <Utensils className="h-5 w-5" />
            </div>
            <div>
              <h2 className="text-xl md:text-2xl font-light text-blue-900 dark:text-blue-300 serif">Culinary <span className="italic">Highlights</span></h2>
              <p className="text-xs uppercase tracking-wider text-slate-400 dark:text-slate-500 font-medium">Essential restaurants, bistros, and authentic eats.</p>
            </div>
          </div>

          <div className="space-y-4">
            {plan.restaurants.map((rest, index) => (
              <div key={index} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-5 shadow-sm space-y-3 hover:border-blue-400/50 dark:hover:border-blue-800/50 transition-colors">
                <div className="flex justify-between items-start gap-2">
                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white text-base serif italic">{rest.name}</h3>
                    <p className="text-xs text-slate-400 mt-0.5 uppercase tracking-wide font-medium">{rest.cuisine}</p>
                  </div>
                  <div className="flex flex-col items-end shrink-0">
                    <span className="inline-flex items-center gap-1 bg-amber-50 dark:bg-amber-950/20 text-amber-600 dark:text-amber-400 text-xs px-2 py-0.5 rounded-sm font-semibold">
                      <Star className="h-3 w-3 fill-amber-500 text-amber-500" /> {rest.rating}
                    </span>
                    <span className="text-xs font-semibold text-slate-500 dark:text-slate-400 mt-1">{rest.priceRange}</span>
                  </div>
                </div>
                <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">
                  {rest.description}
                </p>
                <div className="bg-linear-to-r from-blue-50/50 to-indigo-50/50 dark:from-slate-800 dark:to-slate-800/50 px-3.5 py-2.5 rounded-xl border border-blue-100/30 dark:border-slate-800">
                  <p className="text-xs text-blue-700 dark:text-blue-300 font-bold flex items-center gap-1">
                    <Coffee className="h-3.5 w-3.5" /> Must-Try Dish: <span className="font-semibold">{rest.recommendedDish}</span>
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* 5. Attractions */}
      <div className="space-y-6">
        <div className="flex items-center gap-3 border-b border-slate-200 dark:border-slate-800 pb-4">
          <div className="p-2.5 bg-blue-50 dark:bg-blue-950/30 text-blue-900 dark:text-blue-400 rounded-lg">
            <Compass className="h-5 w-5" />
          </div>
          <div>
            <h2 className="text-2xl md:text-3xl font-light text-blue-900 dark:text-blue-300 serif">Bespoke <span className="italic">Attractions</span></h2>
            <p className="text-xs uppercase tracking-wider text-slate-400 dark:text-slate-500 font-medium">Curated locations and essential sightseeing spots.</p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {plan.attractions.map((attr, index) => (
            <div key={index} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-sm flex flex-col justify-between hover:border-blue-400/50 dark:hover:border-blue-800/50 transition-colors">
              <div className="space-y-3">
                <div className="flex justify-between items-start gap-2">
                  <h3 className="font-semibold text-slate-900 dark:text-white text-lg serif italic">{attr.name}</h3>
                  {attr.cost && (
                    <span className="text-xs font-semibold px-2.5 py-1 bg-slate-100 dark:bg-slate-800 border border-slate-200/50 dark:border-slate-700 rounded-md text-slate-700 dark:text-slate-300">
                      {attr.cost}
                    </span>
                  )}
                </div>
                <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
                  {attr.description}
                </p>
              </div>

              {(attr.duration || attr.highlights) && (
                <div className="pt-4 mt-4 border-t border-slate-100 dark:border-slate-800 grid grid-cols-2 gap-4 text-xs">
                  {attr.duration && (
                    <div>
                      <span className="text-slate-400 uppercase tracking-wider font-semibold block">Duration</span>
                      <span className="font-semibold text-slate-700 dark:text-slate-300 mt-0.5 block">{attr.duration}</span>
                    </div>
                  )}
                  {attr.highlights && (
                    <div>
                      <span className="text-slate-400 uppercase tracking-wider font-semibold block">Key Highlight</span>
                      <span className="font-semibold text-slate-700 dark:text-slate-300 mt-0.5 block truncate" title={attr.highlights}>
                        {attr.highlights}
                      </span>
                    </div>
                  )}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* 6. Travel Logistics, Packing, & Safety */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Logistics (Weather & Transport) */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-sm space-y-6">
          <div className="flex items-center gap-2 border-b border-slate-150 dark:border-slate-800 pb-3">
            <Bus className="h-5 w-5 text-blue-900 dark:text-blue-400" />
            <h3 className="font-light text-blue-950 dark:text-blue-200 text-lg serif italic">Transport & Weather</h3>
          </div>

          <div className="space-y-4">
            <div className="space-y-1.5">
              <span className="text-[10px] uppercase tracking-wider text-slate-400 dark:text-slate-500 font-bold block">Local Transit</span>
              <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">{plan.transportation}</p>
            </div>

            <div className="space-y-1.5 pt-3 border-t border-slate-100 dark:border-slate-800">
              <span className="text-[10px] uppercase tracking-wider text-slate-400 dark:text-slate-500 font-bold block flex items-center gap-1">
                <Cloud className="h-3.5 w-3.5 text-blue-900 dark:text-blue-400" /> Weather Advisory
              </span>
              <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed">{plan.weatherTips}</p>
            </div>
          </div>
        </div>

        {/* Packing Checklist */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-sm space-y-4">
          <div className="flex items-center gap-2 border-b border-slate-150 dark:border-slate-800 pb-3">
            <CheckSquare className="h-5 w-5 text-blue-900 dark:text-blue-400" />
            <h3 className="font-light text-blue-950 dark:text-blue-200 text-lg serif italic">Packing Checklist</h3>
          </div>

          <div className="max-h-60 overflow-y-auto space-y-2.5 pr-2">
            {plan.packingChecklist.map((item, i) => (
              <div key={i} className="flex items-start gap-2.5 text-xs text-slate-700 dark:text-slate-300">
                <CheckSquare className="h-4 w-4 text-blue-900 dark:text-blue-400 mt-0.5 shrink-0" />
                <span>{item}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Safety Tips */}
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-6 shadow-sm space-y-4">
          <div className="flex items-center gap-2 border-b border-slate-150 dark:border-slate-800 pb-3">
            <Shield className="h-5 w-5 text-blue-900 dark:text-blue-400" />
            <h3 className="font-light text-blue-950 dark:text-blue-200 text-lg serif italic">Safety Tips</h3>
          </div>

          <div className="space-y-3">
            {plan.safetyTips.map((tip, i) => (
              <div key={i} className="flex gap-2.5 text-xs text-slate-600 dark:text-slate-300">
                <span className="inline-flex h-1.5 w-1.5 rounded-full bg-blue-900 dark:bg-blue-400 shrink-0 mt-1.5" />
                <span>{tip}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* 7. Action Buttons */}
      <div className="flex flex-wrap items-center justify-center sm:justify-between gap-4 bg-slate-50 dark:bg-slate-800/40 border border-slate-200/50 dark:border-slate-700/50 p-6 rounded-2xl">
        <button
          id="generate-another-btn"
          onClick={onReset}
          className="px-6 py-3 border border-slate-300 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 font-bold rounded-xl transition-all flex items-center gap-2 text-sm focus:outline-hidden"
        >
          <RotateCcw className="h-4 w-4" />
          Generate Another Plan
        </button>

        <div className="flex items-center gap-3 flex-wrap">
          <button
            id="share-plan-btn"
            onClick={handleShare}
            className="px-6 py-3 border border-slate-300 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 font-bold rounded-xl transition-all flex items-center gap-2 text-sm focus:outline-hidden relative"
          >
            <Share2 className="h-4 w-4" />
            Share Trip
            {shareToast && (
              <span className="absolute -top-10 left-1/2 -translate-x-1/2 bg-slate-900 text-white text-[11px] px-2.5 py-1 rounded-sm shadow-md animate-fade-in whitespace-nowrap z-50">
                Mock share link copied!
              </span>
            )}
          </button>

          <button
            id="download-plan-btn"
            onClick={handleDownload}
            className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl transition-all shadow-md flex items-center gap-2 text-sm focus:outline-hidden"
          >
            <Download className="h-4 w-4" />
            Download Trip Plan
          </button>
        </div>
      </div>
    </div>
  );
}
